// ============================================================
// Imagery.
//
// Three photographs exist for this project and no more: the twin towers at
// dusk, the porte-cochère arrival, and the marble lobby. They are the OFFICIAL
// M3M Brabus renders, served from /public/renders with AVIF/WebP derivatives
// generated by scripts/images.mjs and declared in src/lib/renders.generated.js.
//
// Nothing else ships. The interior and amenity slots used to be filled with
// Pexels stock — photographs of other people's buildings, pulled from a third
// party's CDN. That cost ~170 kB of uncacheable cross-origin bytes on the
// homepage's critical path, put three images of the site outside our control,
// and, worse, showed a buyer a flat that is not this flat. On a page selling a
// branded residence that is a credibility problem, not a placeholder. The ids
// are gone rather than commented out.
//
// The consequence is deliberate: where M3M has published no render, a slot now
// falls back to the lobby — the only interior that exists — rather than to a
// stranger's apartment. Any section that can afford to is better off carrying
// NO image and letting type do the work. That precedent is already set: see
// AMENITY_CATEGORIES in src/lib/amenities.js, where `image` is null for every
// category without a render, and src/components/sections/Amenities.jsx, which
// drops the figure and re-flows its grid when it is.
// ============================================================

const TOWER = "/renders/tower.jpg";     // twin towers at dusk, over the landscaped grounds
const ARRIVAL = "/renders/arrival.jpg"; // the porte-cochère, marble wall and water court
const LOBBY = "/renders/lobby.jpg";     // the double-height marble lobby and its lounge

/**
 * Resolve an image source.
 *
 * It once turned a Pexels photo id into a remote CDN URL, which is why every
 * call site still hands it a width. Everything is local now and the width is
 * ignored: Media.jsx picks the derivative from the generated manifest using the
 * caller's `sizes`, which is a truer signal than a number typed into a section.
 * The argument stays so the ~25 call sites keep reading the same.
 *
 * A nullish source resolves to null, not to a broken URL — so a section that
 * has decided to run without an image can simply guard on the result.
 */
export const px = (src, _width) => (typeof src === "string" && src ? src : null);

export const IMG = {
  // ---- The three official renders ----
  tower: TOWER,
  heroExterior: TOWER,
  arrival: ARRIVAL,
  facade: ARRIVAL,
  lobby: LOBBY,
  lobbyWarm: LOBBY,

  // ---- Subjects M3M has not released a render of ----
  // Kept as named keys so call sites still read as what they are asking for,
  // and so the day a real spa or bedroom render arrives it is one line here.
  // Until then they resolve to the lobby: the only published interior, and an
  // honest one. A caption that names a room we cannot show is doing more work
  // than the picture is — those sections should drop the image entirely.
  livingRoom: LOBBY,
  duplexLiving: LOBBY,
  bedroom: LOBBY,
  bedroomDecor: LOBBY,
  spa: LOBBY,
  pool: LOBBY,
  gym: LOBBY,
};
