// ============================================================
// Imagery.
//
// Three photographs exist for this project and no more: the twin towers at
// dusk, the porte-cochère arrival, and the marble lobby. They are the OFFICIAL
// M3M Brabus renders, served from /public/renders with AVIF/WebP derivatives
// generated by scripts/images.mjs and declared in src/lib/renders.generated.js.
//
// Nothing else ships. The interior and amenity slots used to be filled with
// Pexels stock — photographs of other people's buildings, pulled from a third
// party's CDN. That cost ~170 kB of uncacheable cross-origin bytes on the
// homepage's critical path, put three images of the site outside our control,
// and, worse, showed a buyer a flat that is not this flat. On a page selling a
// branded residence that is a credibility problem, not a placeholder. The ids
// are gone rather than commented out.
//
// The consequence is deliberate: where M3M has published no render, a slot now
// falls back to the lobby — the only interior that exists — rather than to a
// stranger's apartment. Any section that can afford to is better off carrying
// NO image and letting type do the work. That precedent is already set: see
// AMENITY_CATEGORIES in src/lib/amenities.js, where `image` is null for every
// category without a render, and src/components/sections/Amenities.jsx, which
// drops the figure and re-flows its grid when it is.
// ============================================================

const TOWER = "/renders/tower.jpg";     // twin towers at dusk, over the landscaped grounds
const ARRIVAL = "/renders/arrival.jpg"; // the porte-cochère, marble wall and water court
const LOBBY = "/renders/lobby.jpg";     // the double-height marble lobby and its lounge

/**
 * Resolve an image source.
 *
 * It once turned a Pexels photo id into a remote CDN URL, which is why every
 * call site still hands it a width. Everything is local now and the width is
 * ignored: Media.jsx picks the derivative from the generated manifest using the
 * caller's `sizes`, which is a truer signal than a number typed into a section.
 * The argument stays so the ~25 call sites keep reading the same.
 *
 * A nullish source resolves to null, not to a broken URL — so a section that
 * has decided to run without an image can simply guard on the result.
 */
export const px = (src, _width) => (typeof src === "string" && src ? src : null);

// ---- Commissioned interior/amenity visualisations ----
// These are project visualisations, not photographs of a finished building, and
// not official M3M renders either. They exist so a section that asks for a
// bedroom shows a bedroom rather than the lobby again. Anything shown from here
// is indicative — see the disclaimer copy that accompanies these sections.
const L = (name) => `/renders/lifestyle/${name}.jpg`;

export const IMG = {
  // ---- The three official renders ----
  tower: TOWER,
  heroExterior: TOWER,
  arrival: ARRIVAL,
  facade: ARRIVAL,
  lobby: LOBBY,
  lobbyWarm: LOBBY,

  // ---- Now covered by a visualisation of the actual subject ----
  livingRoom: L("living-room"),
  duplexLiving: L("sky-terrace-sunset"),
  bedroom: L("master-bedroom"),
  bedroomDecor: L("walk-in-wardrobe"),
  spa: L("master-bathroom"),
  pool: L("rooftop-pool-dusk"),
  gym: L("gym"),
  kitchen: L("kitchen"),
  dining: L("dining-room"),
  clubhouse: L("clubhouse-lounge"),
  theatre: L("home-theatre"),
  games: L("billiards-games-room"),
  garden: L("private-garden-terrace"),
  privateDining: L("private-dining-room"),
  entrance: L("entrance-signage-wall"),
};
